[AlphaCompositing] Add alphaCompositing Optimization Implementation
amishutin/image_proc pull request #1
Opened 2024-02-06 14:37 UTC by Raincwail

* Add three alphaCompositing implementations
* Add script.sh to set environmental variables
* Add TIME_SETUP and TIME_MEASURE macros to performance tests
* Add script.sh for ease of setup
* Move images to 'images' folder

2024-02-06 14:59 UTC, amishutin requested changes

2024-02-06 14:59 UTC, amishutin commented on .gitignore
> +/_build
конец строки

2024-02-06 14:59 UTC, amishutin commented on c_impl.hpp
>  #endif // IMPLEMENTATION_HPP
конец строки

2024-02-06 14:59 UTC, amishutin commented on implementation.cpp
> +#include <iostream>
нужен?

2024-02-06 14:59 UTC, amishutin commented on script.sh
пути везде разные, лучше удалить этот файл

2024-02-06 14:59 UTC, amishutin commented on perf_main.cpp
> +    TIME_MEASURE(c_morphology(src, dst_ref), "C_Impl morphology");
думаю, лучше под разные тесты разные матрицы

2024-02-06 14:59 UTC, amishutin commented on implementation.cpp
> +    for(int vec_block = 0; vec_block < pixelNum; vec_block += vl, pFg += vl, pBg += vl, pA += vl, pDst += vl)
`vl` задается 1 раз как `min(pixelNum, LMUL * VLEN / ELEN)`
тогда цикл по `vec_block` должен проходить до `(pixelNum - leftovers)`
можно задавать с помощью интринсика vsetvlmax

2024-02-06 14:59 UTC, amishutin commented on implementation.cpp
Выглядит хорошо, но можно попробовать с LMUL = 2, 16 регистров должно хватить

2024-02-06 14:59 UTC, amishutin commented on implementation.cpp
Неиспользуемый код лучше удалить

2024-02-07 07:07 UTC, Raincwail commented on implementation.cpp
> +    for(int vec_block = 0; vec_block < pixelNum; vec_block += vl, pFg += vl, pBg += vl, pA += vl, pDst += vl)
Если я буду так делать, если смысл обрабатывать остатки в ифе ниже? По идее все обработается в основном форе, я правильно понимаю?

2024-02-07 07:14 UTC, amishutin commented on implementation.cpp
> +    for(int vec_block = 0; vec_block < pixelNum; vec_block += vl, pFg += vl, pBg += vl, pA += vl, pDst += vl)
Смысл есть, кто же тогда leftovers обработает?
А идти до `pixelNum` мы не можем, т.к. выйдем за границы выделенной памяти для pDst.  Идти нужно до `(pixelNum - leftovers)`, чтобы не выходить за границы.

2024-02-07 07:39 UTC, Raincwail commented on implementation.cpp
По поводу разных lmul, я провел замеры времени относительно различных lmul еще вчера, и выявил следующую тенденцию по времени: m1 == m2 == m4 >> m8.
Не очень понимаю, почему именно на m8 производительность значительно падает.
Сами эксперименты: https://docs.google.com/spreadsheets/d/13THwd8dxaeZbuRTZyI275WHT_AXb3AeOYbOVEfywcR8/edit?usp=sharing.

По поводу неиспользуемого кода: если речь идет про var1, var2 и var3, то они не используются в коде напрямую, но все же необходимы для экспериментов по производительности, поэтому предлагаю их оставить.

2024-02-07 07:48 UTC, amishutin commented on implementation.cpp
Неиспользуемый код будет приводить к warnings с флагом -Wall. Если есть желание его оставить, то можно его обернуть в 
`#if 0`
unused code
`#endif `

2024-02-07 08:00 UTC, Raincwail commented
Учтены все замечания, помимо последнего, к которому есть комментарии.
@amishutin, can you review, please?

2024-02-07 08:02 UTC, Raincwail commented on implementation.cpp
Понял, принял, спасибо!

2024-02-07 08:07 UTC, amishutin approved these changes

2024-02-07 08:07 UTC, amishutin commented
looks good!

2024-02-07 08:07 UTC, merged